<?php

namespace App\Http\Controllers\Admin;
use App\Http\Requests\Admin\CreateUpdateServiceRequest;
use App\Models\Service;
use Illuminate\Http\Request;

class ServiceController extends BaseController
{

    protected $modelClass = Service::class;
    protected $title = 'الخدمات';
    protected $route = 'services';

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    function show(Service $service)
    {
        return redirect()->back()->with('msg','لا يوجد تفاصيل');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUpdateServiceRequest $request)
    {
        //
        return $this->saveData($request->validated());
    }


    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Service $service
     * @return \Illuminate\Http\Response
     */
    public function update(CreateUpdateServiceRequest $request, Service $service)
    {
        //
        return $this->saveData($request->validated(), $service);
    }

    public function saveData($data, $item = null)
    {
        unset($data['image']);
        if (\request()->image) {
            $name = \request()->image->store("original");
            $imgName = resize_image($name);
            if ($imgName)
                $data['image'] = $imgName;
        }
            return parent::saveData($data, $item); // TODO: Change the autogenerated stub
    }

}
